### PR TITLE
Replace cargo generate

### PR DESCRIPTION
**Pull request by emidev98**
This PR will replace [cargo generate](https://github.com/cargo-generate/cargo-generate) with [template-scaffolding](https://github.com/terra-money/template-scaffolding) which is a native JavaScript solution to clone templates and replace the tags from the template with necessary values send as config object.

### CODE REVIEW

**Comment by emidev98** [comment]
Live feature execution
https://user-images.githubusercontent.com/49301655/167382455-3a009c79-d1c8-47a4-82eb-f117dd29b9df.mp4

**Comment by octalmage** [comment]
@emidev98 would you mind running the eslint fix on both code new and the new command? Lots of issues with the style.

**Comment by octalmage** [comment]
@emidev98 would you mind running the eslint fix on both code new and the new command? Lots of issues with the style.

**Comment by emidev98** [comment]
@octalmage I created this issue to modify all staying in only one PR when we have less PRS open https://github.com/terra-money/terrain/issues/69

**Comment by octalmage** [comment]
It makes the code harder to review, might as well start fixing our code moving forward!

**Comment by emidev98** [comment]
Makes totally sense it looked horrible, I have fixed all of them minus https://github.com/terra-money/terrain/security/code-scanning/678, which if I am not mistaking we are addressing it in another branch. Let me know @octalmage  :+1:

**Review by octalmage — APPROVED** [review]
LGTM

**Pull request merged**
